name       : restic
version    : 0.13.1
release    : 19
source     :
    - https://github.com/restic/restic/archive/refs/tags/v0.13.1.tar.gz : 8430f80dc17b98fd78aca6f7d635bf12a486687677e15989a891ff4f6d8490a9
license    : BSD-2-Clause
component  : system.utils
summary    : Fast, secure, efficient backup program
description: |
    restic is a CLI backup program that is fast, efficient and secure.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 restic -t $installdir/usr/bin

    install -Dm00644 doc/man/*.1 -t $installdir/usr/share/man/man1
    install -Dm00644 doc/bash-completion.sh $installdir/usr/share/bash-completion/completions/restic
    install -Dm00644 doc/zsh-completion.zsh $installdir/usr/share/zsh/site-functions/_restic
