name       : restic
version    : 0.7.3
release    : 1
source     :
    - https://github.com/restic/restic/releases/download/v0.7.3/restic-0.7.3.tar.gz : 6d795a5f052b3a8cb8e7571629da14f00e92035b7174eb20e32fd1440f68aaff
license    : BSD-2-Clause
component  : system.utils
summary    : Fast, secure, efficient backup program 
description: |
    restic is a backup program that is fast, efficient and secure.
builddeps  :
    - golang
build      : |
    %make
    ./restic manpage --output-dir doc/man
    ./restic autocomplete --completionfile doc/restic
install    : |
    install -D -m 00755 $workdir/restic $installdir/usr/bin/restic
    install -D -m 00644 $workdir/README.rst $installdir/usr/share/doc/restic/README
    install -D -m 00644 -t $installdir/usr/share/man/man1 $workdir/doc/man/*.1 
    install -D -m 00644 $workdir/doc/restic $installdir/usr/share/bash-completion/completions/restic
