name       : restic
version    : 0.9.4
release    : 11
source     :
    - https://github.com/restic/restic/releases/download/v0.9.4/restic-0.9.4.tar.gz : c7dca90fb6fd83cee8b9f6a2776f5839794341af1953d251bf06a91870be7a8e
license    : BSD-2-Clause
component  : system.utils
summary    : Fast, secure, efficient backup program
description: |
    restic is a backup program that is fast, efficient and secure.
builddeps  :
    - golang
build      : |
    %make
    ./restic generate --man doc/man
    ./restic generate --bash-completion doc/restic
    ./restic generate --zsh-completion doc/_restic
install    : |
    install -D -m 00755 $workdir/restic $installdir/usr/bin/restic
    install -D -m 00644 $workdir/README.rst $installdir/usr/share/doc/restic/README
    install -D -m 00644 -t $installdir/usr/share/man/man1 $workdir/doc/man/*.1
    install -D -m 00644 $workdir/doc/restic $installdir/usr/share/bash-completion/completions/restic
    install -D -m 00644 $workdir/doc/_restic $installdir/usr/share/zsh/site-functions/_restic
