name       : restic
version    : 0.15.2
release    : 22
source     :
    - https://github.com/restic/restic/archive/refs/tags/v0.15.2.tar.gz : 52aca841486eaf4fe6422b059aa05bbf20db94b957de1d3fca019ed2af8192b7
license    : BSD-2-Clause
component  : system.utils
summary    : Fast, secure, efficient backup program
description: |
    restic is a CLI backup program that is fast, efficient and secure.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 restic -t $installdir/usr/bin

    install -Dm00644 doc/man/*.1 -t $installdir/usr/share/man/man1
    install -Dm00644 doc/bash-completion.sh $installdir/usr/share/bash-completion/completions/restic
    install -Dm00644 doc/zsh-completion.zsh $installdir/usr/share/zsh/site-functions/_restic
    install -Dm00644 doc/fish-completion.fish $installdir/usr/share/fish/vendor_completions.d/restic.fish
