name       : restic
version    : 0.15.0
release    : 21
source     :
    - https://github.com/restic/restic/archive/refs/tags/v0.15.0.tar.gz : 85a6408cfb0798dab52335bcb00ac32066376c32daaa75461d43081499bc7de8
license    : BSD-2-Clause
component  : system.utils
summary    : Fast, secure, efficient backup program
description: |
    restic is a CLI backup program that is fast, efficient and secure.
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 restic -t $installdir/usr/bin

    install -Dm00644 doc/man/*.1 -t $installdir/usr/share/man/man1
    install -Dm00644 doc/bash-completion.sh $installdir/usr/share/bash-completion/completions/restic
    install -Dm00644 doc/zsh-completion.zsh $installdir/usr/share/zsh/site-functions/_restic
